TimeshareUISolution/Pages/Admin/Account/Index.cshtml.cs
using APIDataAccess.DTO.ResponseModels;
using APIDataAccess.DTO.ResponseModels.Helpers;
using APIDataAccess.Helpers;
using APIDataAccess.Services.IService;
using APIDataAccess.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using static APIDataAccess.DTO.ResponseModels.Helpers.DynamicModelResponse;

namespace TimeshareUISolution.Pages.Admin.Account
{
    public class IndexModel : PageModel
    {
        private readonly IAccountService _service;
        public static int CurrentPage { get; set; }
        public static int TotalPage { get; set; }
        public int TotalRecord { get; set; }
        public int PageSize { get; set; }
        public string SearchString { get; set; }

        public List<AccountViewModel> AccountList { get; set; }
        public IndexModel(IAccountService service)
        {
            _service = service;
        }
        public IActionResult OnGet(string? number = null, string? filter = null)
        {
            CurrentPage = int.Parse(number != null ? number : "1"); 

            CurrentPage = (CurrentPage < 1)? 1 : CurrentPage;
            CurrentPage = (CurrentPage > TotalPage  && TotalPage != 0? TotalPage : CurrentPage);

            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN))
            {
                return RedirectToPage("/Admin/Login");
            }
            //https://localhost:7246/api/Account/GetListAccount?FirstName=2&page=1
            var accountRespone = _service.GetModelAsync<DynamicModelsResponse<AccountViewModel>>
                (path: "/GetListAccount?FullName=" + filter + "&" + "page=" + CurrentPage, token: user.AccessToken).Result;

            if (accountRespone.Item1 != null)
            {
                if(accountRespone.Item1.Results != null)
                {
                    AccountList = accountRespone.Item1.Results;
                    TotalPage = (int)MathF.Ceiling((float)accountRespone.Item1.Metadata.Total/(float) accountRespone.Item1.Metadata.Size);
                }
                else
                {
                    var errorMessage = accountRespone.Item1.Message;
                    if (errorMessage != null)
                    {
                    }
                }
                
            }
            else
            {
                var errorMessage = accountRespone.Item2;
                if (errorMessage != null)
                {
                }
            }
            return Page();
        }
        public IActionResult OnPost(string userId)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN))
            {
                return RedirectToPage("/Admin/Login");
            }
            var response = _service.Delete<AccountViewModel>(path: $"/DeleteAccountById/{userId}", token: user.AccessToken).Result;
            if (response != null)
            {
                if(response.result == true)
                {
                    TempData["successMessage"] = response.Message;
                    return RedirectToPage("/Admin/Account/Index");
                }
                else
                {
                    TempData["errorMessage"] = response.Message;
                    return RedirectToPage("/Admin/Account/Index");
                }
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                return Page();
            }
        }

        public IActionResult OnGetActivateAccount(string email)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN))
            {
                return RedirectToPage("/Admin/Login");
            }
            var result = HelperFeature.Instance.CallApiAsyncPut("https://localhost:7246/api/Account/ActiveAccount/" + email, user.AccessToken, "").Result;

            if (JsonConvert.DeserializeObject<bool>(result) == false)
            {
                TempData["errorMessage"] = "Server error";
            }
            return Page();
        }

        public IActionResult OnPostSearch()
        {
            string search = Request.Form["search"];
            return OnGet(filter: search);

        }
    }
}

TimeshareUISolution/Pages/Admin/Account/Update.cshtml.cs
using APIDataAccess.DTO.RequestModels;
using APIDataAccess.DTO.ResponseModels;
using APIDataAccess.DTO.ResponseModels.Helpers;
using APIDataAccess.Services.IService;
using APIDataAccess.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace TimeshareUISolution.Pages.Admin.Account
{
    public class UpdateModel : PageModel
    {
        private readonly IAccountService _service;
        public UpdateModel(IAccountService service)
        {
            _service = service;
        }
        public AccountViewModel Account { get; set; }
        public ActionResult OnGet(string accountID)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            //if (user.Value.Role != ((int)AccountRole.ADMIN))
            //{
            //    return RedirectToPage("/Admin/Login");
            //}
            var response = _service.GetModelAsync<ResponseResult<AccountViewModel>>(path: $"/GetAccountById/{accountID}", token: user.AccessToken).Result;
            if (response.Item1 != null)
            {
                if(response.Item1.Value != null)
                {
                    Account = response.Item1.Value;
                }
                else
                {
                    var errorMessage = response.Item1.Message;
                    if (errorMessage != null)
                    {
                        return RedirectToPage("/Admin/Account/Index");
                    }
                }
            }
            else
            {
                var errorMessage = response.Item2;
                if (errorMessage != null)
                {
                    return RedirectToPage("/Admin/Account/Index");
                }
            }
            return Page();
        }
        public IActionResult OnPost(string id,string firstName, string lastName, string email,string phoneNumber, string address, string state, string city, string status, string password, string role)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            //if (user.Value.Role != ((int)AccountRole.ADMIN))
            //{
            //    return RedirectToPage("/Admin/Login");
            //}
            var update = new AccountRequestModel
            {
                FirstName = firstName,
                LastName = lastName,
                FullName = $"{firstName} {lastName}",
                City = city,
                Email = email,
                Phone = phoneNumber,
                Address = address,
                State = state,
                Country = Request.Form["country"],
                Status = int.Parse(status),
                Password = password,
                Role = int.Parse(role)
            };
            var response = _service.Put<AccountRequestModel, AccountViewModel>(update ,path: $"/UpdateAccountById/{id}", token: user.AccessToken).Result;
            if (response != null)
            {
                if(response.result == true)
                {
                    TempData["successMessage"] = response.Message;
                    return Redirect($"/Admin/Account/Update?accountID={id}");
                }
                else
                {
                    OnGet(id);
                    TempData["errorMessage"] = response.Message;
                    return Page();
                }
            }
            else
            {
                OnGet(id);
                TempData["errorMessage"] = "Server error";
                return Page();
            }
        }
    }
}

TimeshareUISolution/Pages/Admin/Account/Index.cshtml
@page
@using APIDataAccess.Utils
@model TimeshareUISolution.Pages.Admin.Account.IndexModel
@{
    Layout = Layout = "_Layout_Admin";
}

<div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="card">
            <h5 class="card-header">List Accounts</h5>
            <div class="table-responsive text-nowrap">
                <table class="table table-borderless">
                    <thead>
                        <tr>
                            <th>Full Name</th>
                            <th>Role</th>
                            <th>Users</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model.AccountList != null && Model.AccountList.Count > 0)
                            {
                                foreach (var account in Model.AccountList)
                                {
                                    <tr>
                                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>@account.FullName</strong></td>
                                        @{
                                            var i = account.Role ?? 0;
                                        }
                                        <td>@DisplayUtils.RoleToString(i)</td>
                                        <td>
                                            <ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center">
                                                <li data-bs-toggle="tooltip"
                                                    data-popup="tooltip-custom"
                                                    data-bs-placement="top"
                                                    class="avatar avatar-xs pull-up"
                                                    title="Lilian Fuller">
                                                    <img src="~/img/avatars/5.png" alt="Avatar" class="rounded-circle" />
                                                </li>
                                                <li data-bs-toggle="tooltip"
                                                    data-popup="tooltip-custom"
                                                    data-bs-placement="top"
                                                    class="avatar avatar-xs pull-up"
                                                    title="Sophia Wilkerson">
                                                    <img src="~/img/avatars/6.png" alt="Avatar" class="rounded-circle" />
                                                </li>
                                                <li data-bs-toggle="tooltip"
                                                    data-popup="tooltip-custom"
                                                    data-bs-placement="top"
                                                    class="avatar avatar-xs pull-up"
                                                    title="Christina Parker">
                                                    <img src="~/img/avatars/7.png" alt="Avatar" class="rounded-circle" />
                                                </li>
                                            </ul>
                                        </td>
                                        <td><span class="badge bg-label-primary me-1">@DisplayUtils.StatusToString(account.Status ?? 0)</span></td>
                                        <td>
                                            <div class="dropdown">
                                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                                    <i class="bx bx-dots-vertical-rounded"></i>
                                                </button>
                                                <div class="dropdown-menu">
                                                    <a class="dropdown-item" href="~/Admin/Account/Update?accountId=@account.AccountId"><i class="bx bx-edit-alt me-1"></i> Edit</a>
                                                    <a class="dropdown-item" onclick="deleteBtn(@account.AccountId)"><i class="bx bx-trash me-1"></i> Delete</a>
                                                    <a class="dropdown-item" asp-page="Index" asp-page-handler="ActivateAccount" asp-route-email="@account.Email"><i class="bx bx-edit-alt me-1"></i>Active account</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No records found</td>
                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div style="height:50px;"></div>

        <div class="pagination">
            <a asp-route-number="@(IndexModel.CurrentPage - 1)">&laquo;</a>
            <a asp-route-number="@IndexModel.CurrentPage" class="active">@IndexModel.CurrentPage</a>
            <a asp-route-number="@(IndexModel.CurrentPage + 1)">&raquo;</a>
        </div>

    </div>
</div>
<form method="post" id="deleteForm">
    <input type="hidden" name="userId" id="userId" />
</form>

<script>
    const deleteForm = document.getElementById('deleteForm');
    var deleteInput = document.getElementById('userId');
    // Click handler
    function deleteBtn(userId) {
        Swal.fire({
            title: 'Bạn chắc chắn không?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Có'
        }).then((result) => {
            if (result.isConfirmed) {

                deleteInput.value = userId;
                // Submit form if user confirmed
                deleteForm.submit();
            }
        })
    }
</script>

TimeshareUISolution/Pages/Admin/Account/Update.cshtml
@page
@model TimeshareUISolution.Pages.Admin.Account.UpdateModel
@{
    Layout = "_Layout_Admin";
}

<div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings /</span> Account</h4>

        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-pills flex-column flex-md-row mb-3">
                    <li class="nav-item">
                        <a class="nav-link active" href="javascript:void(0);"><i class="bx bx-user me-1"></i> Account</a>
                    </li>
                </ul>
                <div class="card mb-4">
                    <h5 class="card-header">Profile Details</h5>
                    <!-- Account -->
                    <div class="card-body">
                        <div class="d-flex align-items-start align-items-sm-center gap-4">
                            <img src="~/img/avatars/1.png"
                                 alt="user-avatar"
                                 class="d-block rounded"
                                 height="100"
                                 width="100"
                                 id="uploadedAvatar" />
                            <div class="button-wrapper">
                                <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                                    <span class="d-none d-sm-block">Upload new photo</span>
                                    <i class="bx bx-upload d-block d-sm-none"></i>
                                    <input type="file"
                                           id="upload"
                                           class="account-file-input"
                                           hidden
                                           accept="image/png, image/jpeg" />
                                </label>
                                <button type="button" class="btn btn-outline-secondary account-image-reset mb-4">
                                    <i class="bx bx-reset d-block d-sm-none"></i>
                                    <span class="d-none d-sm-block">Reset</span>
                                </button>

                                <p class="text-muted mb-0">Allowed JPG, GIF or PNG. Max size of 800K</p>
                            </div>
                        </div>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body">
                        <form method="POST">
                            <div class="row">
                                <input type="hidden" name="id" value="@Model.Account.AccountId" />
                                <input type="hidden" name="password" value="@Model.Account.Password" />
                                <input type="hidden" name="role" value="@Model.Account.Role" />
                                <input type="hidden" name="status" value="@Model.Account.Status" />
                                <div class="mb-3 col-md-6">
                                    <label for="firstName" class="form-label">First Name</label>
                                    <input class="form-control"
                                           type="text"
                                           id="firstName"
                                           name="firstName"
                                           value="@Model.Account.FirstName"
                                           autofocus />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="lastName" class="form-label">Last Name</label>
                                    <input class="form-control" type="text" name="lastName" id="lastName" value="@Model.Account.LastName" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="email" class="form-label">E-mail</label>
                                    <input class="form-control"
                                           type="text"
                                           id="email"
                                           name="email"
                                           value="@Model.Account.Email"
                                           placeholder="john.doe@example.com" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label" for="phoneNumber">Phone Number</label>
                                    <div class="input-group input-group-merge">
                                        <span class="input-group-text">VN (+84)</span>
                                        <input type="text"
                                               id="phoneNumber"
                                               name="phoneNumber"
                                               class="form-control"
                                               value="@Model.Account.Phone" />
                                    </div>
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="address" class="form-label">Address</label>
                                    <input type="text" class="form-control" id="address" name="address" value="@Model.Account.Address" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="state" class="form-label">City</label>
                                    <input class="form-control" type="text" id="city" name="city" value="@Model.Account.City" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="state" class="form-label">State</label>
                                    <input class="form-control" type="text" id="state" name="state" value="@Model.Account.State" />
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label" for="country">Country</label>
                                    <select id="country" name="country" class="select2 form-select">
                                        <option value="">Select</option>
                                        <option value="Australia">Australia</option>
                                        <option value="Bangladesh">Bangladesh</option>
                                        <option value="Belarus">Belarus</option>
                                        <option value="Brazil">Brazil</option>
                                        <option value="Canada">Canada</option>
                                        <option value="China">China</option>
                                        <option value="France">France</option>
                                        <option value="Germany">Germany</option>
                                        <option value="India">India</option>
                                        <option value="Indonesia">Indonesia</option>
                                        <option value="Israel">Israel</option>
                                        <option value="Italy">Italy</option>
                                        <option value="Japan">Japan</option>
                                        <option value="Korea">Korea, Republic of</option>
                                        <option value="Mexico">Mexico</option>
                                        <option value="Philippines">Philippines</option>
                                        <option value="Russia">Russian Federation</option>
                                        <option value="South Africa">South Africa</option>
                                        <option value="Thailand">Thailand</option>
                                        <option value="Turkey">Turkey</option>
                                        <option value="Ukraine">Ukraine</option>
                                        <option value="United Arab Emirates">United Arab Emirates</option>
                                        <option value="United Kingdom">United Kingdom</option>
                                        <option value="United States">United States</option>
                                    </select>
                                </div>

                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2">Save changes</button>
                                <button type="reset" class="btn btn-outline-secondary">Cancel</button>
                            </div>
                        </form>
                    </div>
                    <!-- /Account -->
                </div>
            </div>
        </div>
    </div>