TimeshareUISolution/Pages/Admin/Department/Create.cshtml.cs
using APIDataAccess.DTO.RequestModels;
using APIDataAccess.DTO.ResponseModels;
using APIDataAccess.DTO.ResponseModels.Helpers;
using APIDataAccess.Services.IService;
using APIDataAccess.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using static APIDataAccess.DTO.ResponseModels.Helpers.DynamicModelResponse;

namespace TimeshareUISolution.Pages.Admin.Department
{
    public class CreateModel : PageModel
    {
        private readonly IDepartmentService _service;
        private readonly IAccountService _accountService;
        public CreateModel(IDepartmentService service, IAccountService accountService)
        {
            _service = service;
            _accountService = accountService;
        }
        public Dictionary<int, string> ConstructionType { get; set; }
        public Dictionary<int, string> Status { get; set; }
        public List<AccountViewModel> ListAccount { get; set; }
        public IActionResult OnGet()
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN))
            {
                RedirectToPage("/Admin/Login");
            }
            var contructionType = _service.GetModelAsync<EnumViewModel>
                (path: "/GetDepartmentConstructionType", token: user.AccessToken).Result;
            if (contructionType.Item1 != null)
            {
                if (contructionType.Item1.Results != null)
                {
                    ConstructionType = contructionType.Item1.Results;
                }
                else
                {
                    TempData["errorMessage"] = contructionType.Item1.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                return RedirectToPage("/Admin/Department/Index");
            }
            var status = _service.GetModelAsync<EnumViewModel>
                (path: "/GetDepartmentStatuses", token: user.AccessToken).Result;
            if (status.Item1 != null)
            {
                if (status.Item1.Results != null)
                {
                    Status = status.Item1.Results;
                }
                else
                {
                    TempData["errorMessage"] = status.Item1.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                return RedirectToPage("/Admin/Department/Index");
            }
            var account = _accountService.GetModelAsync<DynamicModelsResponse<AccountViewModel>>
                               (path: "/GetListAccount", token: user.AccessToken).Result;
            if (account.Item1.Results != null)
            {
                ListAccount = account.Item1.Results;
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                return RedirectToPage("/Admin/Department/Index");
            }
            return Page();
        }
        public IActionResult OnPost(string name, string address, string city, string country, string state, int floor, decimal price, string description, int capacity)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN))
            {
                RedirectToPage("/Admin/Login");
            }
            var request = new DepartmentRequestModel
            {
                DepartmentName = name,
                Address = address,
                City = city,
                Country = country,
                State = state,
                Floors = floor,
                Price = price,
                Description = description,
                ConstructionType = int.Parse(Request.Form["constructionType"]),
                Status = int.Parse(Request.Form["status"]),
                OwnerId = int.Parse(Request.Form["ownerId"]),
                Capacity = capacity,
            };
            var response = _service.PostWithResponse<ResponseResult<DepartmentViewModel>, DepartmentRequestModel>(request ,path: "/CreateDepartment", user.AccessToken).Result;
            if(response.Item1 != null)
            {
                if(response.Item1.Value != null)
                {
                    TempData["successMessage"] = response.Item1.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }
                else
                {
                    TempData["errorMessage"] = response.Item1.Message;
                    OnGet();
                    return Page();
                }
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                OnGet();
                return Page();
            }
        }
    }
}

TimeshareUISolution/Pages/Admin/Department/Edit.cshtml.cs
using APIDataAccess.DTO.RequestModels;
using APIDataAccess.DTO.ResponseModels;
using APIDataAccess.DTO.ResponseModels.Helpers;
using APIDataAccess.Services.IService;
using APIDataAccess.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace TimeshareUISolution.Pages.Admin.Department
{
    public class EditModel : PageModel
    {
        private readonly IDepartmentService _service;
        private readonly IOwnerService _ownerService;
        public EditModel(IDepartmentService service, IOwnerService ownerService)
        {
            _service = service;
            _ownerService = ownerService;
        }
        public DepartmentViewModel Department { get; set; }
        public OwnerViewModel Owner { get; set; }   
        public Dictionary<int, string> Enum { get; set; }
        public Dictionary<int, string> Status { get; set; }
        public IActionResult OnGet(string departmentId)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN) && user.Value.Role != ((int)AccountRole.STAFF))
            {
                RedirectToPage("/Admin/Login");
            }
            var response = _service.GetModelAsync<ResponseResult<DepartmentViewModel>>(path: $"/GetDepartment/{departmentId}", token: user.AccessToken).Result;
            if (response.Item1 != null)
            {
                if (response.Item1.Value != null)
                {
                    Department = response.Item1.Value;
                    var enumResponse = _service.GetModelAsync<EnumViewModel>(path: $"/GetDepartmentConstructionType", token: user.AccessToken).Result;
                    if (enumResponse.Item1 != null)
                    {
                        if (enumResponse.Item1.Results != null)
                        {
                            Enum = enumResponse.Item1.Results;
                        }
                        else
                        {
                            TempData["errorMessage"] = enumResponse.Item1.Message;
                            return RedirectToPage("/Admin/Department/Index");
                        }
                    }
                    else
                    {
                        TempData["errorMessage"] = "Server error";
                        return RedirectToPage("/Admin/Department/Index");
                    }
                    var statusResponse = _service.GetModelAsync<EnumViewModel>(path: $"/GetDepartmentStatuses", token: user.AccessToken).Result;
                    Status = statusResponse.Item1.Results;
                    var ownerResponse = _ownerService.GetModelAsync<ResponseResult<OwnerViewModel>>(path: $"/GetOwner/{Department.OwnerId.ToString()}", token: user.AccessToken).Result;
                    if (ownerResponse.Item1 != null)
                    {
                        if (ownerResponse.Item1.Value != null)
                        {
                            Owner = ownerResponse.Item1.Value;
                        }
                        else
                        {
                            TempData["errorMessage"] = ownerResponse.Item1.Message;
                            return RedirectToPage("/Admin/Department/Index");
                        }
                    }
                    else
                    {
                        TempData["errorMessage"] = "Server error";
                        return RedirectToPage("/Admin/Department/Index");
                    }
                    return Page();
                }
                else
                {
                    TempData["errorMessage"] = response.Item1.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }

            }
            else
            {
                TempData["errorMessage"] = "Server error";
                return Page();
            }
        }
        public IActionResult OnPost(string ownerId, string departmentName, string address, string city, string state, string country, int capacity, int floor, decimal price, string description, int departmentId)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN) && user.Value.Role != ((int)AccountRole.STAFF))
            {
                return RedirectToPage("/Admin/Login");
            }
            var update = new DepartmentRequestModel
            {
                OwnerId = int.Parse(ownerId),
                DepartmentName = departmentName,
                Address = address,
                City = city,
                State = state,
                Country = country,
                Capacity = capacity,
                Floors = floor,
                Price = price,
                Description = description,
                ConstructionType = int.Parse(Request.Form["constructionType"]),
                Status = int.Parse(Request.Form["status"])
            };
            var response = _service.Put<DepartmentRequestModel, DepartmentViewModel>(update, path: $"/UpdateDepartment/{departmentId}", token: user.AccessToken).Result;
            if (response != null)
            {
                if (response.result == true)
                {
                    TempData["successMessage"] = response.Message;
                    return RedirectToPage("Index");

                    //return Redirect($"/Admin/Department/Edit?departmentId={departmentId}");
                }
                else
                {
                    OnGet(departmentId.ToString());
                    TempData["errorMessage"] = response.Message;
                    return Page();
                }
            }
            else
            {
                OnGet(departmentId.ToString());
                TempData["errorMessage"] = "Server error";
                return Page();
            }

        }

        public IActionResult OnPostDelete(string deleteid)
        {
            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN) && user.Value.Role != ((int)AccountRole.STAFF))
            {
                return RedirectToPage("/Admin/Login");
            }
            var response = _service.Delete<ResponseResult<DepartmentViewModel>>(path: $"/DeleteDepartment/{deleteid}", token: user.AccessToken).Result;
            if(response != null)
            {
                if(response.result == true)
                {
                    TempData["successMessage"] = response.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }
                else
                {
                    TempData["errorMessage"] = response.Message;
                    return RedirectToPage("/Admin/Department/Index");
                }
            }
            else
            {
                TempData["errorMessage"] = "Server error";
                OnGet(deleteid);
                return Page();
            }
        }
    }
}

TimeshareUISolution/Pages/Admin/Department/Index.cshtml.cs
using APIDataAccess.DTO.ResponseModels;
using APIDataAccess.DTO.ResponseModels.Helpers;
using APIDataAccess.Services.IService;
using APIDataAccess.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using static APIDataAccess.DTO.ResponseModels.Helpers.DynamicModelResponse;

namespace TimeshareUISolution.Pages.Admin.Department
{
    public class IndexModel : PageModel
    {
        private readonly IDepartmentService _service;
        public static int CurrentPage { get; set; }
        public static int TotalPage { get; set; }
        public int PageSize { get; set; } = 3;
        public IndexModel(IDepartmentService service)
        {
            _service = service;
        }
        public int PageNumber { get; set; }
        public List<DepartmentViewModel> DepartmentList { get; set; }
        public IActionResult OnGet(string? number = null, string? filter = null)
        {

            CurrentPage = int.Parse(number != null ? number : "1");

            CurrentPage = (CurrentPage < 1) ? 1 : CurrentPage;
            CurrentPage = (CurrentPage > TotalPage && TotalPage != 0 ? TotalPage : CurrentPage);

            var userStr = HttpContext.Session.GetString("User");
            if (userStr == null || userStr.Count() == 0)
            {
                return RedirectToPage("/Admin/Login");
            }
            var user = JsonConvert.DeserializeObject<UserLoginResponse>(userStr);
            if (user == null)
            {
                return RedirectToPage("/Admin/Login");
            }
            if (user.Value.Role != ((int)AccountRole.ADMIN) && user.Value.Role != ((int)AccountRole.STAFF))
            {
                return RedirectToPage("/Admin/Login");
            }
            var response = _service.GetModelAsync<DynamicModelsResponse<DepartmentViewModel>>
                (path: "/GetListDepartment?DepartmentName=" + filter + "&" + "page="  + CurrentPage + "&pageSize=" +PageSize, token: user.AccessToken).Result;

            TotalPage = (int)MathF.Ceiling((float)response.Item1.Metadata.Total / (float)response.Item1.Metadata.Size);

            if (response.Item1 != null)
            {
                if(response.Item1 != null)
                {
                    DepartmentList = response.Item1.Results;
                    PageNumber = response.Item1.Metadata.Page;
                }
                else
                {
                    var errorMessage = response.Item1.Message;
                    if (errorMessage != null)
                    {
                    }
                }
                
            }
            return Page();
        }

        public IActionResult OnPostSearch()
        {
            string search = Request.Form["search"];
            return OnGet(filter: search);
        }
    }
}

TimeshareUISolution/Pages/Admin/Department/Edit.cshtml
@page
@using APIDataAccess.Utils
@model TimeshareUISolution.Pages.Admin.Department.EditModel
@{
    Layout = "_Layout_Admin";
}

<div class="content-wrapper">
    <div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
        <!-- Sign Up Card -->
        <div class="card" style="padding:10px;">
            <div class="card-body">
                <h5 class="card-title">Edit Department</h5>
                <form method="post">
                    <input type="hidden" name="departmentId" value="@Model.Department.DepartmentId" />
                    <input type="hidden" name="ownerId" value="@Model.Owner.OwnerId" />
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="ownerName" placeholder="Owner Name" value="@Model.Owner.OwnerName" disabled>
                                <label for="name">Owner Name</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="departmentName" placeholder="Department Name" value="@Model.Department.DepartmentName">
                                <label for="email">Department Name</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" name="address" placeholder="Address" value="@Model.Department.Address">
                        <label for="address">Address</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" name="city" placeholder="City" value="@Model.Department.City">
                        <label for="city">City</label>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="state" placeholder="State" value="@Model.Department.State">
                                <label for="state">State</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="country" placeholder="Country" value="@Model.Department.Country">
                                <label for="country">Country</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="number" class="form-control" name="capacity" placeholder="Capacity" value="@Model.Department.Capacity">
                                <label for="capacity">Capacity</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="number" class="form-control" name="floor" placeholder="Floors" value="@Model.Department.Floors">
                                <label for="floor">Floors</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="number" class="form-control" name="price" placeholder="Price" value="@Model.Department.Price">
                                <label for="price">Price</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <select id="constructionType" name="constructionType" class="select2 form-select">
                                    @{
                                        foreach (var item in Model.Enum)
                                        {
                                            if (item.Key == Model.Department.ConstructionType)
                                            {
                                                <option selected value="@item.Key">
                                                    @item.Value
                                                </option>
                                            }

                                            {
                                                <option value="@item.Key">
                                                    @item.Value
                                                </option>
                                            }

                                        }
                                    }
                                </select>
                                <label for="constructionType">Construction Type</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" name="description" placeholder="Description" value="@Model.Department.Description">
                        <label for="city">Description</label>
                    </div>
                    <div class="form-floating mb-3">
                        <select id="status" name="status" class="select2 form-select">
                            @{
                                foreach (var item in Model.Status)
                                {
                                    if (item.Key == Model.Department.Status)
                                    {
                                        <option selected value="@item.Key">
                                            @item.Value
                                        </option>
                                    }
                                    else
                                    {
                                        <option value="@item.Key">
                                            @item.Value
                                        </option>
                                    }

                                }
                            }
                        </select>
                        <label for="city">Status</label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-signup w-100">Save</button>
                </form>
                <form method="post" id="deleteForm" asp-page-handler="Delete" style="padding-top:10px;">
                    <input type="hidden" name="deleteId" id="deleteId"/>
                    <a class="btn btn-danger btn-signup w-100" onclick="deleteBtn(@Model.Department.DepartmentId)">Delete</a>
                </form>
            </div>
        </div>
        <!-- Your existing sign-up form code goes here -->
    </div>
</div>
<script>
    const deleteForm = document.getElementById('deleteForm');
    var deleteInput = document.getElementById('deleteId');
    // Click handler
    function deleteBtn(deleteId) {
        Swal.fire({
            title: 'Bạn chắc chắn không?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Có'
        }).then((result) => {
            if (result.isConfirmed) {
                deleteInput.value = deleteId;
                // Submit form if user confirmed
                deleteForm.submit();
            }
        })
    }
</script>

<style>
    @@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

    .logo-container {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        margin-top: 15px;
    }

    .house-icon {
        width: 30px;
        height: 30px;
    }

    .website-name {
        margin-left: 5px;
        font-size: 20px;
        font-weight: bold;
        color: forestgreen;
    }

    a {
        text-decoration: none;
    }

    .card {
        padding: 5px;
        border-radius: 20px; /* Ensures consistent border-radius */
        min-height: 500px;
        width: 80%;
    }

    .card-title {
        padding: 20px 0; /* Added padding to the top and bottom */
        font-size: 25px;
        font-weight: bold;
    }

    .outer-card {
        font-family: 'Poppins', sans-serif;
        width: 70%;
        padding: 40px; /* Space around the inner card */
        border-radius: 25px; /* Larger radius for the outer card */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Soft shadow for depth */
        display: flex; /* Align inner card to the left */
        align-items: center; /* Center inner card vertically */
        justify-content: flex-start; /* Start alignment */
        min-height: 60vh; /* Minimum height for outer card */
    }

    .card-container {
        width: 50%; /* Adjust as needed */
        height: 100%; /* Equal height */
    }

    .form-check .form-check-input {
        width: 15px;
        height: 15px;
        margin-top: 0.3rem;
        margin-left: 0;
    }

    .form-check-label {
        font-size: 0.9rem;
        margin-left: 0.5rem;
    }

    input[type="text"],
    input[type="email"],
    input[type="password"] {
        border-radius: 12px; /* Adjusts the roundness */
        /* Optional additional styles for a consistent look */
        border: 1px solid #ced4da;
        padding: .375rem .75rem;
    }

    .btn-signup {
        padding: 0.9rem 1.5rem; /* Larger top/bottom and left/right padding */
        font-size: 1rem; /* Keeping the text size the same */
        border-radius: 15px;
    }

    .sign-up-option {
        display: flex;
        align-items: center;
        text-align: center;
        color: rgba(108, 117, 125, 0.5); /* Lighter text color with reduced opacity */
        margin-top: 20px; /* Space above the text */
        font-size: 0.9rem; /* Adjust the size as needed */
        margin-bottom: 20px;
    }

        .sign-up-option::before,
        .sign-up-option::after {
            content: '';
            flex: 1;
            border-bottom: 1px solid rgba(108, 117, 125, 0.5); /* Lighter line color with reduced opacity */
            margin: 0px 10px; /* Space between the text and lines */
        }

    .logo-button {
        border: none;
        border-radius: 50%; /* Makes the button circular */
        width: 50px; /* Adjust as needed */
        height: 50px; /* Adjust as needed */
    }

        .logo-button img {
            width: 100%;
            height: auto;
        }

    .button-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: row;
    }

</style>
@if (TempData["successMessage"] != null)
{
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '@TempData["successMessage"]',
            showConfirmButton: true,
            timer: null,
            allowOutsideClick: false
        })
    </script>
}
@if (TempData["errorMessage"] != null)
{
    <script>
        Swal.fire({
            position: 'center',
            icon: 'error',
            title: '@TempData["errorMessage"]',
            showConfirmButton: true,
            timer: null,
            allowOutsideClick: false
        })
    </script>
}